version: "3.8"
services:
  sgevc:
    build:
      context: .
      dockerfile: Dockerfile
    shm_size: '16gb'
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]