services:
  sgevc:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/home/containeruser/sgevc
    shm_size: '16gb'
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]